// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElContainer: typeof import('element-plus/es')['ElContainer'];
        ElDialog: typeof import('element-plus/es')['ElDialog'];
        ElDropdown: typeof import('element-plus/es')['ElDropdown'];
        ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
        ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
        ElFooter: typeof import('element-plus/es')['ElFooter'];
        ElForm: typeof import('element-plus/es')['ElForm'];
        ElFormItem: typeof import('element-plus/es')['ElFormItem'];
        ElHeader: typeof import('element-plus/es')['ElHeader'];
        ElIcon: typeof import('element-plus/es')['ElIcon'];
        ElInput: typeof import('element-plus/es')['ElInput'];
        ElMain: typeof import('element-plus/es')['ElMain'];
        Footer: typeof import('./src/components/shared/Footer.vue')['default'];
        Header: typeof import('./src/components/shared/Header.vue')['default'];
        HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
        LoginButton: typeof import('./src/components/LoginButton.vue')['default'];
        Menu: typeof import('./src/components/Menu.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        ServiceWorker: typeof import('./src/components/ServiceWorker.vue')['default'];
        ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default'];
        VueUse: typeof import('./src/components/VueUse.vue')['default'];
    }
}

export {};
