// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElContainer: typeof import('element-plus/es')['ElContainer'];
        ElDialog: typeof import('element-plus/es')['ElDialog'];
        ElFooter: typeof import('element-plus/es')['ElFooter'];
        ElForm: typeof import('element-plus/es')['ElForm'];
        ElFormItem: typeof import('element-plus/es')['ElFormItem'];
        ElHeader: typeof import('element-plus/es')['ElHeader'];
        ElInput: typeof import('element-plus/es')['ElInput'];
        ElMain: typeof import('element-plus/es')['ElMain'];
        ElPageHeader: typeof import('element-plus/es')['ElPageHeader'];
        ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm'];
        Footer: typeof import('./src/components/Footer.vue')['default'];
        Header: typeof import('./src/components/Header.vue')['default'];
        HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
        Menu: typeof import('./src/components/Menu.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        UserInfo: typeof import('./src/components/UserInfo.vue')['default'];
        VueUse: typeof import('./src/components/VueUse.vue')['default'];
    }
}

export {};
